// Code generated by goctl. DO NOT EDIT.
package types

type SearchRequest struct {
	OrderID string `form:"order_id" validate:"required"`
}

type SearchResponse struct {
	OrderID  string `json:"order_id"`
	Status   int    `json:"status"`
	Username string `json:"username"`
}
