version: '3.5'

# 服务容器配置
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.29
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mall # for database creation automatically
    ports:
      - "127.0.0.1:13306:3306"  
    
  redis7:
    container_name: redis7
    image: "bitnami/redis:latest"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    
  etcd:
    container_name: etcd
    image: "quay.io/coreos/etcd:v3.5.5"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCDCTL_API=3
    ports:
      - "127.0.0.1:12379:2379"  

  consul:
    image: hashicorp/consul:1.13
    container_name: consul
    ports:
      # 映射到本地 8500 端口
      - "127.0.0.1:18500:8500"
    # 
    command: agent -ui -client 0.0.0.0 -dev